### ISSUE TITLE
Remove user selection on img to prevent blues selection box

### ISSUE THREAD

**Issue by whyleonardo** [Super-Patos-Hackaton/frontend#15]
## Description
Currently, users can select images on the website, which leads to the appearance of a blue selection box around the image. This selection box is visually disruptive and detracts from the overall user experience. To enhance the visual presentation and improve user interaction.

## Motivation
Preventing image selection can reduce user frustration. Users might unintentionally drag or click on images, leading to an unnecessary selection box appearing. This can be distracting and may confuse users who are not familiar with why this box appears.

![image](https://github.com/Super-Patos-Hackaton/frontend/assets/94463485/4393c878-3203-4d07-bc81-8be8ac4da891)

## Proposed Solution

```css
img {
  @apply select-none;
}
```

## Tasks
- [ ] Edit `globals.css` file and apply tailwindcss rules

**Comment by roberto-juniorjp** [comment]
Issue has been solved and merged.
